// <auto-generated />
namespace JobMtaani.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class idcardnumber1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(idcardnumber1));
        
        string IMigrationMetadata.Id
        {
            get { return "201609132003467_idcardnumber1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
