// <auto-generated />
namespace JobMtaani.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Categoryname : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Categoryname));
        
        string IMigrationMetadata.Id
        {
            get { return "201607191943035_Categoryname"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
